// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8ZfR36gVKz6rCMejeICZc3zeKDXfBUCM',
    appId: '1:620335847686:web:158aa579639eb89a1c2687',
    messagingSenderId: '620335847686',
    projectId: 'flight-booking-app-f69f9',
    authDomain: 'flight-booking-app-f69f9.firebaseapp.com',
    storageBucket: 'flight-booking-app-f69f9.firebasestorage.app',
    measurementId: 'G-2JMB2WX8GD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA09Po3n3eQEacZfvOy7EFFQVZrtSEuojw',
    appId: '1:620335847686:android:c5f2d2fbdbb340481c2687',
    messagingSenderId: '620335847686',
    projectId: 'flight-booking-app-f69f9',
    storageBucket: 'flight-booking-app-f69f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB09rLdcuiZ6AAzlEc95f97k9ZgqMg2NP4',
    appId: '1:620335847686:ios:10c61f4bac3675d11c2687',
    messagingSenderId: '620335847686',
    projectId: 'flight-booking-app-f69f9',
    storageBucket: 'flight-booking-app-f69f9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB09rLdcuiZ6AAzlEc95f97k9ZgqMg2NP4',
    appId: '1:620335847686:ios:10c61f4bac3675d11c2687',
    messagingSenderId: '620335847686',
    projectId: 'flight-booking-app-f69f9',
    storageBucket: 'flight-booking-app-f69f9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8ZfR36gVKz6rCMejeICZc3zeKDXfBUCM',
    appId: '1:620335847686:web:c9ec81def8d0403c1c2687',
    messagingSenderId: '620335847686',
    projectId: 'flight-booking-app-f69f9',
    authDomain: 'flight-booking-app-f69f9.firebaseapp.com',
    storageBucket: 'flight-booking-app-f69f9.firebasestorage.app',
    measurementId: 'G-KTDXTLBMG3',
  );

}